# Generated by Django 4.0.6 on 2023-01-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('country', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dubai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('numberPerson', models.IntegerField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('acctype', models.CharField(max_length=100)),
                ('queries', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='India',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('numberPerson', models.IntegerField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('acctype', models.CharField(max_length=100)),
                ('queries', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Singapore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('numberPerson', models.IntegerField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('acctype', models.CharField(max_length=100)),
                ('queries', models.CharField(max_length=100)),
            ],
        ),
    ]
