# Generated by Django 4.0.6 on 2023-01-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('country', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
