# Generated by Django 4.0.6 on 2023-01-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('phno', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('d1', models.DateField()),
                ('d2', models.DateField()),
            ],
        ),
    ]
