# Generated by Django 4.1.2 on 2023-01-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="india", name="State",),
    ]
