# Generated by Django 4.1.2 on 2023-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_india_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dubai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("numberPerson", models.IntegerField()),
                ("sdate", models.DateField()),
                ("edate", models.DateField()),
                ("acctype", models.CharField(max_length=100)),
                ("queries", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Singapore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("numberPerson", models.IntegerField()),
                ("sdate", models.DateField()),
                ("edate", models.DateField()),
                ("acctype", models.CharField(max_length=100)),
                ("queries", models.CharField(max_length=100)),
            ],
        ),
    ]
